create table book (
    id int generated by default as identity,
    title varchar not null,
    author varchar not null,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),
    primary key (id)
);

create table users (
    id int generated by default as identity,
    name varchar not null,
    lastname varchar not null,
    email varchar not null,
    role varchar not null,
    salary decimal not null,
    primary key (id)
);